' Gambas module file

Public Sub abgleich(Comand As String[], Sender As String)

  Dim c As Comand
  Dim s As String
  Dim arg As String[]
  Dim ausgabe As String

  arg = Comand

  If GlobalDatas.CammandData.Length > 0 Then

    For Each C In GlobalDatas.CammandData
      If c.ComandName == arg[0] Then

        Select Case c.Template.Type

          Case 0
            '- - - - - - - - Normal Output - - - - - - - -

            If c.ComandName == arg[0] Then
              irc.irc_send_Message(c.Ausgabe, Main.Kannal)
            Endif

          Case 1
            '- - - - - - - - msg Code Word - - - - - - - -

            For Each s In Split(C.Ausgabe, " ")

              If s = "$msg" Then
                ausgabe = ausgabe & " " & argToMsg(arg, 1)
              Else
                ausgabe = ausgabe & " " & s
              Endif

            Next
            irc.irc_send_Message(ausgabe, Main.Kannal)
          Case 2
            '- - - - - - - - Rmd Comand - - - - - - - -

            'Rand(0, 100)
            For Each s In Split(C.Ausgabe, " ")

              If s = "$rmd" Then
                ausgabe &= " " & Rand(0, 100)
              Else
                ausgabe &= " " & s
              Endif

            Next
            irc.irc_send_Message(ausgabe, Main.Kannal)

        End Select
      Endif
    Next

  Endif

End

Public Sub argToMsg(arg As String[], Delete As Integer) As String

  Dim s As String
  Dim a As String
  Dim i As Integer

  For i = Delete DownTo 0 Step 1

    arg.Delete(0)

  Next
  For Each s In arg

    If Not a = Null Then
      a = a & " " & s
    Else
      a = s
    Endif
  Next
  Return a

End
