' Gambas module file

'- - - - - - - - - - - - - - - Public - Varialen - - - - - - - - - - - -

'- - - - - - - - - - - - - - - Private - Varialen - - - - - - - - - - - -
Private Server As New ServerSocket("/tmp/Bisambot/Server", 1) As "CommandServer"
Public Client As New Socket[]
Private $iId As Integer

Public Sub Initiieren()

  Server.Type = Net.Internet
  Server.Port = 10469
  Server.Listen(1)
  If Server.Status = Net.Active And Server.Type = Net.Internet Then
    main.GesamtLog.Print("Tcp Command Server Starting At Port 10469")
  Endif

  Wait 0.1
  main.GesamtLog.Print("Please Connect via TCP on this Server to Command The Bot")

End

Public Sub CommandServer_Connection(RemoteHostIP As String)

  Dim Obj As Socket
  Dim SBuf As String

  If Server.Status <= Net.Inactive Then Return

  Obj = Server.Accept()
  Obj.Blocking = False
  Inc $iId

  Obj.Tag = [$iId, 0, ""]
  Client.Clear()
  Client.Add(Obj)
  main.GesamtLog.Print("Socket " & Obj.Tag[0] & " Accept")
  SBuf = "Hello on the Bisabot Server on Version " & Application.Version & "!\n The Commans come In a few seconds."
  Write #Obj, sBuf, Len(sBuf)
  Wait 2
  sBuf = "/Clear"
  Write #Obj, sBuf, Len(sBuf)
  Wait 0.1
  SBuf = "The Commands for Conntroll the Bot a : \n START -- Connect the Bot on the Twitch Chat. \n STOP -- Stop the Bot and Close the Programm. \n JOIN [Channal_Name] -- Leave the Currend Channel and Switch too the aver. \n TC [Chat_Message] -- Send a Message via the Bot to the Twitch Chat.\n HELP -- to see this Message"
  Write #Obj, sBuf, Len(sBuf)

End

Public Sub Socket_Read()

  Dim sBuf As String
  Dim sa As String
  Dim SplitsBuf As String[]
  Dim iInd As Integer
  Dim k As Command

  If Last.Status <> Net.Connected Then Return
  Read #Last, sBuf, Lof(Last)
  main.GesamtLog.Print("Socket #" & Last.Tag[0] & " --> " & sBuf & "\n")

  SplitsBuf = Split(SBuf, " ")

  If sBuf = "START" Then
    main.GesamtLog.Print("Startig IRC Socket With Twitch Chat")
    Main.TwitchJoin()
  Endif

  If SplitsBuf[0] == "Command" Then
    CommandEdit.Abfrage(SplitsBuf)
    sBuf = "HELP"

  Endif

  If sBuf = "STOP" Then
    sBuf = "/Clear"
    Write #Client[0], sBuf, Len(sBuf)
    Wait 0.1
    sBuf = "The Bot will now shutdown"
    Write #Client[0], sBuf, Len(sBuf)
    irc.Close()
    Main.Close()
  Endif

  If SplitsBuf[0] = "JOIN" Then

    main.GesamtLog.Print("Join to Channel #" & SplitsBuf[1])
    irc.Join(SplitsBuf[1])
    Main.Kannal = SplitsBuf[1]

  Endif

  If SplitsBuf[0] = "TC" Then
    SplitsBuf.Remove(0)

    For Each sBuf In SplitsBuf
      sa &= sBuf & " "
    Next
    irc.irc_send_Message(sa, Main.Kannal)

  Endif

  If sBuf = "HELP" Then
    sBuf = "/Clear"
    Write #Client[0], sBuf, Len(sBuf)
    Wait 0.1
    SBuf = "The Commands for Conntroll the Bot a : \n START -- Connect the Bot on the Twitch Chat. \n STOP -- Stop the Bot and Close the Programm. \n JOIN [Channal_Name] -- Leave the Currend Channel and Switch too the aver. \n TC [Chat_Message] -- Send a Message via the Bot to the Twitch Chat.\n HELP -- to see this Message"
    Write #Client[0], sBuf, Len(sBuf)
  Endif

  Last.Tag[1] = 0
  Last.Tag[2] = sBuf

Catch
  main.Gesamtlog.addError(Error.Text & " in " & Error.Where)
  ' SBuf = "The Commands for Conntroll the Bot a : \n START -- Connect the Bot on the Twitch Chat. \n STOP -- Stop the Bot and Close the Programm. \n JOIN [Channal_Name] -- Leave the Currend Channel and Switch too the aver. \n TC [Chat_Message] -- Send a Message via the Bot to the Twitch Chat.\n HELP -- to see this Message"
  ' If Server.Status = Net.Connected Then
  '   Write #Last, sBuf, Len(sBuf)
  ' Endif

End
