' Gambas module file

'- - - - - - - - - - - - - - - - - - Public Var - - - - - - - - - - - - -
Public MySock As New Socket As "Chat"
Public Songrequestlist As New Songrequest[]
Public Kannal As String = "bisam97"
Public Gesamtlog As Loger
'- - - - - - - - - - - - - - - - - - Privat var - - - - - - - - - - - - -

Private OAuth As String
Private Nick As String = "bisasambot"
Private NameText As New String[]
Private Gifeway As New String[]
Private YTIDList As New String[]
Private Songrequestrowlist As New String[][]
Private YTTimera As New String[]
Private YTTimerzeit As New String[]
Private CurrentSong As Songrequest
Private ButtenPress As Boolean
Private sr As New Timer(1000)
Private sraktivator As New Timer(100)
Private Timer1 As New Timer(1000)
Private YtKey As String
Private SongCloutKey As String

Public Sub Main()

  botStartUp.CreateDirs()

  Gesamtlog = New Loger(User.Home & "/.bisabot/logs")
  Gesamtlog.Print("All directories that are used in " & User.Home & "/.bisabot")
  Gesamtlog.Print("Starting")

  If Args.Count <> 2 Then

    Gesamtlog.Print("Error Please Tipe: " & Application.Name & " [Twitch Channel]")
    Quit
  Else
    Gesamtlog.Print("Starting Phase 1")
    botStartUp.LoadCommands()
    botStartUp.LoadViwerlist()
    Kannal = Args[1]
    Gesamtlog.Print("Loadig API Keys")
    YtKey = File.Load(botStartUp.LoadApis("http://bisam97.de/APIKeys/GoogleAPIKey"))
    OAuth = File.Load(botStartUp.LoadApis("http://bisam97.de/APIKeys/twitchAPIkey"))
    Shell "rm /tmp/Bisambot/api" Wait
    LocalCommandSocket.Initiieren()

    Gesamtlog.Print("Bot initation was successful")

    Form_Open()

    ' Gesamtlog.Print( "Startig IRC Socket With Twitch Chat"
    ' Button2_Click()

  Endif

End

Public Sub TwitchJoin()

  Gesamtlog.Print("Load Viewer....")
  botStartUp.loadViewers(Kannal)
  PointsHours.enabelTimer()
  Gesamtlog.Print("Viewer was Loaded successful")
  Timer1.Enabled = True
  Timer1.Start
  irc.Irc_Twitch_Join(nick, OAuth, Kannal)
  irc.irc_send_Message(Nick & " jetzt Online. Hallo OpieOP", Kannal)
  Gesamtlog.Print("IRC Socket successful Open")

End

Public Sub Chat_Read()

  Dim stmop As String
  Dim ssend As String
  Dim Command As String[]
  Dim Sender As String

  Timer1.Stop

  Read #MySock, stmop, Lof(MySock)
  ssend = stmop

  NameText = Split(stmop, "!", "@", False, True)
  Gesamtlog.Print(NameText[1])
  stmop = Split(NameText[0], ":", " ", True)[0] & " : " & Split(NameText[1], " ", ":", True)[3]
  Gesamtlog.Print(stmop)

  '- - - - - - - - - - - - - - - - - - Spliten - - - - - - - - - - - - - - - - - - - - - -

  NameText = Split(ssend, "!", "@", False, True)
  ssend = Split(Split(NameText[1], " ", ":", True)[3], "\r")[0]
  Sender = Split(stmop, ":")[0]
  Command = Split(ssend, " ")

  '- - - - - - - - - - Ash TOen - - - - - - - - - - -
  If Command[0] == "!ash" And If LCase(Sender) = LCase$("ash_ketchum34") Then

    irc.irc_send_Message("/timeout ash_ketchum34 6", Kannal) ' .timeout 600 ash_ketchum34

  Endif
  '- - - - - - - - - - - - - - - - - - - - - Giveway - - - - - - - - - - - - - - - - - - -

  ' If gifeHashtake.ReadOnly Then
  '   If ssend = gifeHashtake.Text Then
  '     TextArea2.Text = Split(NameText[0], ":", " ", True)[0] & "\n" & TextArea2.Text
  '   Endif
  ' Endif

  '- - - - - - - - - - - - - - - - - - - - Songrequest - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  If Command[0] == "!sr" Or Command[0] == "!songrequest"
    Msongrequest(Command, Sender)
  Endif

  '- - - - - - - - - - - - - - - - - - - - Currendsong - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  If Command[0] == "!currentsong" Then
    irc.irc_send_Message("@" & Sender & (" --> Derzeit Läuft: '") & CurrentSong.Title & ("' Gewünscht von ") & CurrentSong.vonUser, Kannal)
  Endif

  '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - CostemCommand - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  commandAction.abgleich(Command, Sender)

  '- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  If Not ButtenPress Then
    Timer1.Start
  Endif

Catch
  'Message.Error(Error.Text & "\n" & Error.Code & "\n" & Error.Where, "ok")

  Gesamtlog.addError(Error.Text & CStr(Error.Code) & Error.Where)

  If Not ButtenPress Then
    Timer1.Start
  Endif

  If Error.Text == "Stream is closed" And Not ButtenPress Then
    irc.Irc_Twitch_Join(Nick, OAuth, Kannal)
  Endif

End

Public Sub Close()

  Button7_Click

End

Public Sub Button7_Click()

  Dim C As Command

  ButtenPress = True
  Timer1.Stop
  botShutdown.saveCommand()
  botShutdown.saveViewerStats()
  Wait 1
  Sav_SR()
  MySock.Close
  Gesamtlog.ErrorPrinter()
  Quit
Catch
  Print Error.Text
  Print Error.Where
  Quit

End

Public Sub Button4_Click()

  ' gifeHashtake.ReadOnly = True
  ' irc.irc_sendMessage("Um am Giveway mit zu machen muesst ihr " & gifeHashtake.Text & " eingeben.viel Glueck ", Kannal)

End

Public Sub Button5_Click()

  '   gifetimer.Stop

End

Public Sub Button6_Click()

  '   gifetimer.Stop
  '   gifeHashtake.ReadOnly = False

End

Public Sub gifetimer_Timer()

End

Public Sub Button3_Click()

  '   Gifeway = Split(TextArea2.Text, "\n")
  '   Gifewaywinner.Text = Gifeway[Rand(Gifeway.Length - 1)]

End

Public Sub Form_Open()

  Dim YTID As String

  ButtenPress = False
  'YTID = "-ShXz0qKdAw"

  '   WebView1.HTML = "<iframe width='300' height='163' src='https://www.youtube.com/embed/" & YTID & "?autoplay=1&rel=0&amp;vq=mobile' frameborder='0' allowfullscreen></iframe>"

End

Public Sub Expander2_Hide()

  '   Expander3.Visible = True
  '   Expander4.Visible = True

End

Public Sub Expander3_Hide()

  '   Expander4.Visible = True

End

Public Sub Expander3_Show()

  '   Expander4.Visible = False

End

Private Sub Msongrequest(I As String[], Sender As String)

  Dim TempS As New String[]
  Dim Zeit As Integer
  Dim Title As String
  Dim SongTemp As Songrequest
  Dim TempStringA As New String[]

  Dim YTID As String

  If Left(I[1], 3) == "htt" Or Left(I[1], 3) == "www" Then
    If Left(I[1], 13) == "https//youtu." Or Left(I[1], 12) == "http//youtu." Then
      YTID = Split(I[1], "/")[3]
    Else
      Gesamtlog.Print(Left(I[1], 13))
      YTID = Split(I[1], "=&")[1]
    Endif
    Gesamtlog.Print(YTIDList.Find(YTID))
    If YTIDList.Find(YTID) = -1 Then

      TempS.Add(Sender)
      TempS.Add(YTID)
      YTIDList.Add(TempS[1])
      Songrequestrowlist.Add(TempS)
      'sraktivator.Start

    Else

      irc.irc_send_Message("@" & Sender & (" --> Deine Request ist schon in der Liste"), Kannal)

    Endif

    TempStringA = Songrequestrowlist[0]
    Songrequestrowlist.Remove(0)
    Sender = TempStringA[0]
    YTID = TempStringA[1]

    Gesamtlog.Print(YTID)

    File.Save("/tmp/Bisambot/YTTimer.txt", "")
    Shell "curl --output '/tmp/Bisambot/YTTimer.txt' 'https://www.googleapis.com/youtube/v3/videos?part=contentDetails&id=" & YTID & "&key='" & YtKey Wait

    YTTimera = Split(File.Load("/tmp/Bisambot/YTTimer.txt"), "\n:\" ", Null, True)
    YTTimerzeit = Split(YTTimera[YTTimera.Find("duration") + 1], "PTHMS", "*", True)

    File.Save("/tmp/Bisambot/YTTimer.txt", "")
    Shell "curl --output '/tmp/Bisambot/YTTimer.txt' 'https://www.googleapis.com/youtube/v3/videos?id=" & YTID & "&key=AIzaSyDMFKfGbfrPgppcoq_6mwVg-X-mHRQxJFI&fields=items(id,snippet(channelId,title,categoryId),statistics)&part=snippet,statistics'" Wait

    YTTimera = Split(File.Load("/tmp/Bisambot/YTTimer.txt"), "\n:\"", Null, True)
    Title = YTTimera[YTTimera.Find("title") + 2]

    Zeit = ZeitErrechenen()
    If Zeit < 1800000 Then

      '       Playlist.Add(Title)
      SongTemp = New Songrequest(Int(Rnd(1, 50000)), Sender, YTID, Title, Zeit)
      Songrequestlist.Add(SongTemp)

      irc.irc_send_Message("@" & Sender & (" --> Das Lied: '") & Title & ("' wurde Erfolgreich Hinzugefügt"), Kannal)

    Else

      irc.irc_send_Message("@" & Sender & (" --> Dein Lied ist zu Lang DansGame"), Kannal)

    Endif
    sr.Start

  Endif

  Gesamtlog.Print(False)

End

Public Sub sr_Timer()

  Dim YTID As String
  Dim S As Songrequest

  sr.Stop
  ' If Playlist.Count > 0 Then
  '   If Not sr.Delay = 1000 Then
  '
  '     Playlist.Remove(0)
  '
  '   Endif
  ' Endif
  sr.Delay = 1000

  If Songrequestlist.Length > 0 Then

    CurrentSong = Songrequestlist[0]
    Songrequestlist.Remove(0)
    YTIDList.Remove(0)

    YTID = CurrentSong.VideoID
    sr.Delay = CurrentSong.Time

    '     WebView1.HTML = ""
    '     WebView1.HTML = "<iframe width='300' height='163' src='https://www.youtube.com/embed/" & YTID & "?autoplay=1&rel=0&amp;vq=mobile' frameborder='0' allowfullscreen></iframe>"

  Endif

  sr.Start

End

Public Sub ZeitErrechenen() As Integer

  Dim Sec As Integer

  If YTTimerzeit.Length == 3 Then
    Sec = YTTimerzeit[0] * 60 * 60
    YTTimerzeit.Remove(0)
  Endif
  If YTTimerzeit.Length == 2 Then
    Sec += YTTimerzeit[0] * 60
    YTTimerzeit.Remove(0)
  Endif
  If YTTimerzeit.Length == 1 Then

    Sec += YTTimerzeit[0]
    YTTimerzeit.Remove(0)
    Sec *= 1000
  Endif
  Return Sec

End

Public Sub Button8_Click()

  sr.Trigger

End

Public Sub Sav_SR()

  Dim S As Songrequest
  Dim TempString As String

  If Not Exist(User.Home & "/.bisabot") Then

    Mkdir User.Home & "/.bisabot"

  Endif

  For Each S In Songrequestlist

    TempString &= s.OutputForSave & "\n"
    Wait 0.1

  Next
  File.Save(User.Home & "/.bisabot/songrequest.sr", TempString)

End

Public Sub Button1_Click()

End

Public Sub sraktivator_Timer()

End
