' Gambas module file

Private ViewTimer As New Timer(6000) As "ViewTimer"

Public Sub ViewTimer_Timer()

  Dim a As Viewer[]

  botStartUp.loadViewers(Main.Kannal)
  getViwerChanges()

End

Public Sub enabelTimer()

  ViewTimer.Start()

End

Public Sub getViwerChanges()

  Dim v As Viewer

  For Each v In GlobalDatas.ActivViewerList

    v.addPoints(GlobalDatas.adder)
    v.addMinuts()
    Main.Gesamtlog.Print(v.userName & " wurde 1 Minute gutgeschrieben")

  Next

End
